# site settings
title: Jesus Zarate
subtitle: by HTML5 UP
email: jesuseduardoz.4751@gmail.com
description: Computer Science student at California State University <br /> Stanislaus interested in working in Information Technology
url: "https://jesusz4751.github.io"
baseurl: ""
author:
street_address: ""
city: Turlock
state: CA
zip_code: 95382
country: United States of America
phone: (209) 417-4411

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
